img1 = imread('test/goldenbridge/goldengate-01.png');
img2 = imread('test/goldenbridge/goldengate-02.png');
C1 = corner_detector(img1);
C2 = corner_detector(img2);
[x1, y1, ~] = anms(C1, 1000);
[x2, y2, ~] = anms(C2, 1000);
[descs1, x1, y1] = feat_desc(img1, x1, y1);
[descs2, x2, y2] = feat_desc(img2, x2, y2);
match = feat_match(descs1, descs2);
mask = match ~= -1;
match = match(mask);
x1 = x1(mask); y1 = y1(mask); x2 = x2(match); y2 = y2(match);
[H, idx] = ransac_est_homography(x1, y1, x2, y2, 3);
showMatchedFeatures(img1, img2, [x1(idx), y1(idx)], [x2(idx), y2(idx)], 'montage');
